name: Gateway Pipeline

on:
  push:
    branches:
      - cicd

jobs:
    build-and-push:
      name: check code
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

    docker:
      name: build and push docker image
      runs-on: ubuntu-latest
      needs: [ build-and-push ]
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
      
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: docker
            file: /Dockerfile
            push: true
            tags: codimates/ead:latest